apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: wordcount-app
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: docker.io/library/custom-spark:v0.0.1
  imagePullPolicy: Never
  mainApplicationFile: "gs://matheusjerico-spark-scripts/wordcount.py"
  sparkVersion: 3.5.3
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    instances: 1
    cores: 1
    memory: 512m