# sparkapplication-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-sparkapplication-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sparkapplication-manager
subjects:
  - kind: ServiceAccount
    name: airflow-worker   # Replace with your Airflow service account name
    namespace: airflow    # Replace with the namespace where Airflow is deployed
